# (весь префикс как выше...)

      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Rust release
        working-directory: seed-brute
        run: cargo build --release
